"""Render this warehouse's bus matrix into `docs/WAREHOUSE.md`.

The derivation is `modern_data_stack.bus_matrix`, which knows nothing about this
project. Here live the constants: which schema holds the published layer, and
which holes in the matrix are already known.

In `publish/`, not `scripts/`, because it must re-run whenever a mart is added
or a key renamed; `tests/test_bus_matrix.py` fails if the rendered block is stale.

The declared holes are not an allowlist of things that are fine: each reason
says whether the hole is a boundary or a defect to fix.
"""

from __future__ import annotations

import sys
from pathlib import Path

from modern_data_stack import bus_matrix
from modern_data_stack.paths import dbt_manifest_path, project_root

SCHEMA = "marts"

DOC_PATH = "docs/WAREHOUSE.md"
MARKER_BEGIN = "<!-- bus-matrix:begin -->"
MARKER_END = "<!-- bus-matrix:end -->"

# Facts that conform to no dimension at all, and why. `tests/test_bus_matrix.py`
# asserts this is exactly the set the manifest produces, in both directions — so
# a new orphan fails, and so does fixing one without deleting its entry.
KNOWN_UNCONFORMED: dict[str, str] = {}


def matrix() -> bus_matrix.BusMatrix:
    """The matrix for this warehouse's published layer."""
    return bus_matrix.build(dbt_manifest_path(), schema=SCHEMA)


def render(built: bus_matrix.BusMatrix | None = None) -> str:
    """The markdown block, markers included, ready to drop into the doc."""
    built = built or matrix()
    parts = [
        MARKER_BEGIN,
        "",
        "<!-- Generated by `just bus-matrix`. Do not edit between the markers. -->",
        "",
        bus_matrix.to_markdown(built),
        "",
    ]
    notes = bus_matrix.key_notes(built)
    if notes:
        parts += ["Notes:", "", *(f"- {note}" for note in notes), ""]
    if KNOWN_UNCONFORMED:
        parts += ["Facts conforming to no dimension:", ""]
        parts += [f"- `{fact}` — {why}" for fact, why in sorted(KNOWN_UNCONFORMED.items())]
        parts += [""]
    parts += [MARKER_END]
    return "\n".join(parts)


def write_doc(doc_path: str | Path | None = None) -> Path:
    """Replace the marked block in the doc, leaving everything around it alone.

    Refuses rather than appends when the markers are missing: a generator that
    silently adds a second copy of its own output is how a doc ends up with two
    matrices that disagree.
    """
    path = Path(doc_path) if doc_path else project_root() / DOC_PATH
    text = path.read_text()
    start, end = text.find(MARKER_BEGIN), text.find(MARKER_END)
    if start == -1 or end == -1:
        raise RuntimeError(f"{path} has no {MARKER_BEGIN} / {MARKER_END} block to fill")
    path.write_text(text[:start] + render() + text[end + len(MARKER_END) :])
    return path


def main() -> int:
    written = write_doc()
    built = matrix()
    print(
        f"wrote the bus matrix into {written}: "
        f"{len(built.facts)} facts x {len(built.dimensions)} conformed dimensions"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
